
-- Drop existing tables to ensure clean slate
DROP TABLE IF EXISTS "ratings" CASCADE;
DROP TABLE IF EXISTS "sales" CASCADE;
DROP TABLE IF EXISTS "customers" CASCADE;
DROP TABLE IF EXISTS "creditcards" CASCADE;
DROP TABLE IF EXISTS "genres_in_movies" CASCADE;
DROP TABLE IF EXISTS "genres" CASCADE;
DROP TABLE IF EXISTS "stars_in_movies" CASCADE;
DROP TABLE IF EXISTS "stars" CASCADE;
DROP TABLE IF EXISTS "movies" CASCADE;

-- 1. Movies Table
CREATE TABLE "movies" (
    "id" VARCHAR(10) PRIMARY KEY, -- tconst
    "title" VARCHAR(100) NOT NULL,
    "year" INTEGER NOT NULL,
    "director" VARCHAR(100) NOT NULL
);

-- 2. Stars Table
CREATE TABLE "stars" (
    "id" VARCHAR(10) PRIMARY KEY, -- nconst
    "name" VARCHAR(100) NOT NULL,
    "birthYear" INTEGER
);

-- 3. Stars in Movies
CREATE TABLE "stars_in_movies" (
    "starId" VARCHAR(10) NOT NULL REFERENCES "stars"("id") ON DELETE CASCADE,
    "movieId" VARCHAR(10) NOT NULL REFERENCES "movies"("id") ON DELETE CASCADE,
    PRIMARY KEY ("starId", "movieId")
);

-- 4. Genres Table
CREATE TABLE "genres" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(32) NOT NULL
);

-- 5. Genres in Movies
CREATE TABLE "genres_in_movies" (
    "genreId" INTEGER NOT NULL REFERENCES "genres"("id") ON DELETE CASCADE,
    "movieId" VARCHAR(10) NOT NULL REFERENCES "movies"("id") ON DELETE CASCADE,
    PRIMARY KEY ("genreId", "movieId")
);

-- 6. Credit Cards
CREATE TABLE "creditcards" (
    "id" VARCHAR(20) PRIMARY KEY,
    "firstName" VARCHAR(50) NOT NULL,
    "lastName" VARCHAR(50) NOT NULL,
    "expiration" DATE NOT NULL
);

-- 7. Customers
CREATE TABLE "customers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstName" VARCHAR(50) NOT NULL,
    "lastName" VARCHAR(50) NOT NULL,
    "ccId" VARCHAR(20) REFERENCES "creditcards"("id") ON DELETE SET NULL,
    "address" VARCHAR(200) NOT NULL,
    "email" VARCHAR(50) NOT NULL,
    "password" VARCHAR(20) NOT NULL
);

-- 8. Sales
CREATE TABLE "sales" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customerId" INTEGER NOT NULL REFERENCES "customers"("id") ON DELETE CASCADE,
    "movieId" VARCHAR(10) NOT NULL REFERENCES "movies"("id") ON DELETE CASCADE,
    "saleDate" DATE NOT NULL
);

-- 9. Ratings
CREATE TABLE "ratings" (
    "movieId" VARCHAR(10) PRIMARY KEY REFERENCES "movies"("id") ON DELETE CASCADE,
    "rating" FLOAT NOT NULL,
    "numVotes" INTEGER NOT NULL
);

-- Indexes for Performance
CREATE INDEX idx_movies_title ON "movies" USING GIN (to_tsvector('english', "title"));
CREATE INDEX idx_movies_year ON "movies" ("year");
CREATE INDEX idx_stars_name ON "stars" USING GIN (to_tsvector('english', "name"));
CREATE INDEX idx_ratings_votes ON "ratings" ("numVotes" DESC);

-- Reload Schema Cache
NOTIFY pgrst, 'reload schema';
